name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest Lab01a/Lab01a.py
        python -m unittest Lab01b/part1.py
        python -m unittest Lab01b/part2.py
        python -m unittest Lab02/part1.py
        python -m unittest Lab02/part2.py